option nolabel;
libname aa "D:\The Application of SAS in Financial Research\SAS data\monthly price";
data a;
   set aa.price;
      if m=12  and  y>2000 then  output;
run;
proc sort data=a;by y;
run;
proc rank data=a out=a groups=2;
   var mv;
   ranks size;
   by y;
run;
proc npar1way data=a;
   var volum value ret turn pb;
   class size;
   ods output WilcoxonTest=t ;
run;
proc univariate data=a noprint;
   var volum value ret turn pb;
   class size;
   output out=m median=volum value ret turn pb;
run;
proc transpose data=m out=m;
   var volum value ret turn pb;
   id size;
run;
data t;
   set t;
      retain order 0;
      if variable^=lag(variable) then order=order+1;
run;
proc transpose data=t out=t;
   var nvalue1;
   id name1;
   by order variable;
run;
data m;
   merge t m;
      if pl_wil<0.01 then dif=round(_0-_1,0.001)||"***";
      else if pl_wil<0.05 then dif=round(_0-_1,0.001)||"**";
      else if  pl_wil<0.1 then dif=round(_0-_1,0.001)||"*";
      else dif=round(_0-_1,0.001)||"";
	  rename _0=G1;
	  rename _1=G2;
      keep variable _0 _1 dif;
run;

proc sort data=a;by y size;
run;
proc npar1way data=a;
   var volum value ret turn pb;
   class size;
   by y;
   ods output WilcoxonTest=t ;
run;
proc univariate data=a noprint;
   var volum value ret turn pb;
   class size;
   by y;
   output out=m median=volum value ret turn pb;
run;
proc transpose data=m out=m;
   var volum value ret turn pb;
   id size;
   by y;
run;
data t;
   set t;
      retain order 0;
      if variable^=lag(variable) then order=order+1;
run;
proc transpose data=t out=t;
   var nvalue1;
   id name1;
   by y order variable;
run;
data m;
   merge t m;
      if pl_wil<0.01 then dif=round(_0-_1,0.001)||"***";
      else if pl_wil<0.05 then dif=round(_0-_1,0.001)||"**";
      else if  pl_wil<0.1 then dif=round(_0-_1,0.001)||"*";
      else dif=round(_0-_1,0.001)||"";
	  rename _0=G1;
	  rename _1=G2;
      keep y variable _0 _1 dif;
run;
%inc "D:\The Application of SAS in Financial Research\CH09\program_cn\npar.sas";
%npar(volum value ret turn pb,4,size,y,a,b);
%npar(volum value ret turn pb,2,size, ,a,c);
