%macro NeweyWest(in,out,x,time,lag);
proc sort data=&in;by &time;
run;
proc transpose data=&in out=&out;
var &x;
by &time;
run;
proc sort data=&out;by _name_ &time;
run;
PROC MODEL data=&out;
PARMS a;
col1 = a;
FIT col1 /GMM KERNEL=(BART,%eval(&lag+1),0);
INSTRUMENTS a;
by _name_;
ods output parameterestimates=para;
quit;
data &out;
set para;
if probt<0.01 then e=round(estimate,0.001)||'***';
else if probt<0.05 then e=round(estimate,0.001)||'**';
else if probt<0.1 then e=round(estimate,0.001)||'*';
else e=round(estimate,0.001)||'';
tv='('||left(round(tvalue,0.01)||')');
run;
proc transpose data=&out out=&out;
var e tv;
id _name_;
run;
data &out;
set &out;
lag=&lag;
run;
%mend;
