DM'LOG;CLEAR;OUT;CLEAR';
option notes nolabel;
libname aa 'D:\The Application of SAS in Financial Research\SAS data\monthly price';
data a;
   set aa.price;
      if nmiss(ret,pb,turn)^=0 then delete;
      month=y*100+m;
      if y=2006 then output;
      keep code month ret pb turn;
run;
proc sort data=a;by code;
run;
proc means noprint data=a;
   var ret;by code;
   output out=code n=n;
run;
data a;
   merge a code;by code;
run;
proc sort data=a;by   code month;
run;
proc panel data=a (where=(n>1)) ;
   model ret=turn pb/bp bp2;
   id code month;
run;
proc panel data=a (where=(n>1));
   model ret=turn pb/fixone;
   id code month;
run;
proc sort data=a;by month code;
run;
proc panel data=a (where=(n>1));
   model ret=turn pb/fixone ;
   id  month code;
run;
proc panel data=a (where=(n>1));
   model ret=turn pb/fixtwo ;
   id  month code;
run;
