%macro FM(bit);
proc transpose data=mean out=b;
by _model_;
id _stat_;
run;
data b;
set b;
t=mean/(std / (n**0.5) );
if t^=. then tvalue='('||left(round(t,0.01)||')');
if mean^=. then do;
if _name_^='_ADJRSQ_' then do;
if abs(t)>2.58 then esti=round(mean,10**-&bit)||'***';
else if 2.58>=abs(t)>1.96 then esti=round(mean,10**-&bit)||'**';
else if 1.96>=abs(t)>1.65 then esti=round(mean,10**-&bit)||'*';
else esti=round(mean,10**-&bit)||'';
end;
else do;
esti=round(mean*100,0.01)||'%';
end;
end;
else do;
delete;
end;
keep _model_ _name_ esti tvalue;
run; 
data t;
set b;
t=_n_;
if _model_='MODEL1' then output;
keep _name_ t;
run;
proc sort data=t;by _name_;
run;
proc sort data=b;by _name_;
run;
data b;
merge b t;by _name_;
run;
proc sort data=b;by t _name_;
run;
proc transpose data=b out=esti;
var esti;
id _model_;
by t _name_;
run;
proc transpose data=b out=tvalue;
var tvalue;
id _model_;
by t _name_;
run;
data esti;
set esti;
type=1;
run;
data tvalue;
set tvalue nobs=x;
if t=x then delete;
type=2;
_name_='';
run;
data FM;
set esti tvalue;by t type;
drop t type model1;
run;
%mend;
