
libname aa 'I:\The Application of SAS in Financial Research\SAS data\fund data';
libname bb 'I:\The Application of SAS in Financial Research\SAS data\four factor';


data rm;
   set bb.factor;
      if y<1987 then delete;
      drop smb hml mom mturn;
run;
data rm;
   set rm;
      t=_n_;
run;
proc sort data=rm;by y m;
run;
data a;
   merge rm aa.fundret;by y m;
      rirf=ret-rf;
      rmrf=rm-rf;
      TM=rmrf**2;
      if rmrf>=0 then HM=rmrf; else HM=0;
      if rirf=. then delete;
run;
proc sort data=a;by fund;
run;

%let year=2;
%macro a;
   proc datasets noprint;
      delete 	fund_performance;
   quit;
   %do i=&year*12 %to 252;
      data b;
         set a;
            if     &i-(&year)*12+1<=t<=&i then output;
      run;
      proc sort data=b;by fund;
      run;
      proc means noprint data=b;
         var rirf;
         by fund;
         output out=c(drop=_type_ _freq_) mean=Erirf std=std n=n;
         /*caculate the expected return and standard deviation*/
      run;
      proc reg noprint data=b outest=d;
         model rirf=rmrf;
         by fund;
      quit;

      data fund;
         merge  c d;by fund;
            Treynor=Erirf/rmrf;
            Sharpe=Erirf/std;
            Jensen=intercept;
            t=&i;
            if n=&year*12 then output;
            keep fund treynor sharpe jensen t;
      run;
      proc append base=fund_performance data=fund;
      quit;
      proc sort;by t;
      run;
   %end;
   data fund_performance; 
      merge fund_performance rm ;by t;
         if m=12 then output; /*only output data of end of the year*/
      run;
   proc sort data=a out=code (keep=fund t);by fund descending t;
   run;
   data code;
      set code; by fund;
         endt=t;
         if first.fund then output;
         drop t;
   run;
   proc sort data=fund_performance;by fund;
   run;
   data fund_performance;
      merge fund_performance code;by fund;
         if t=. then delete;
         if t<=endt then output;
         drop t endt;
   run;
   proc means mean t;
      var  treynor sharpe jensen;
      class fund;
   run;
%mend a;
%a;
proc reg data=a;
   model rirf=rmrf TM;
   model rirf=rmrf HM;
   by fund;
quit;
