
libname aa 'I:\The Application of SAS in Financial Research\SAS data\monthly price';
data a;
   set aa.price;
      month=y*100+m;
      if  month>=200207 then change=1;else change=0;
      keep ret turn change;
run; 
proc sort data=a;by change;
run;
proc reg data=a noprint outest=k(keep=_p_ ) adjrsq;
   model ret=turn;
   output out=a r=r1;
run;
proc reg data=a noprint ;
   model ret=turn;
   by change;
   output out=a r=r2;
run;
data a;
   set a;
      ESS1=r1**2;
      ESS2=r2**2;
run;
proc means noprint;
   var ESS1 ESS2;
   output out=b(drop=_type_ _freq_) sum=ESS1 ESS2 n=N;
run;
data b;
   merge b k;
      Chow=(((ESS1-ESS2)/_p_)/(ESS2/(N-2*_p_)));
      ProbF=1-probf(Chow,_p_,N-2*_p_);
      keep Chow ProbF;
run;
proc print data=b;
quit;
