
libname aa "D:\The Application of SAS in Financial Research\SAS data\fund data";
libname bb "D:\The Application of SAS in Financial Research\SAS data\four factor";
data rm;
   set bb.factor;
      if y<1987 then delete;
      drop smb hml mom mturn;
run;
data rm;
   set rm;
      t=_n_;
run;
proc sort data=rm;by y m;
run;
data a;
   merge rm aa.fundret;by y m;
      rirf=ret-rf;
      rmrf=rm-rf;
      TM=rmrf**2;
      if rmrf>=0 then HM=rmrf; else HM=0;
      if rirf=. then delete;
run;
proc sort data=a;by name;
run;

%let year=2;
%macro a;
   proc datasets noprint;
      delete 	fund_performance;
   quit;
   %do i=&year*12 %to 252;

      proc means noprint data=a(where=(  &i-(&year)*12+1<=t<=&i);
         var rirf;
         by name;
         output out=c(drop=_type_ _freq_) mean=Erirf std=std n=n;
         /*计算预期的风险溢酬以及标准偏差*/
      run;
      proc reg noprint data=a(where=(  &i-(&year)*12+1<=t<=&i) outest=d;
         model rirf=rmrf;
         by name;
      quit;
      data fund;
         merge  c d;by name;
            Treynor=Erirf/rmrf;
            Sharpe=Erirf/std;
            Jensen=intercept;
            t=&i;
            if n=&year*12 then output;
            keep name treynor sharpe jensen t;
      run;
      proc append base=fund_performance data=fund;
      quit;
      proc sort;by t;
   %end;
   data fund_performance;
      merge fund_performance rm ;by t;
         if m=12 then output; /*若不要只是年底的数据则可以删除之*/
   run;
   proc sort data=a out=code (keep=name t);by name descending t;
   run;
   data code;
      set code; by name;
         endt=t;
         if first.name then output;
      drop t;
   run;
   proc sort data=fund_performance;by name;
   run;
   data fund_performance;
      merge fund_performance code;by name;
         if t=. then delete;
         if t<=endt then output;
         drop t endt;
   run;
   proc means mean t;
      var  treynor sharpe jensen;
      class name;
   run;
%mend a;
%a;
proc reg data=a;
   model rirf=rmrf TM;
   model rirf=rmrf HM;
   by name;
quit;
