data a;
   do i=1 to 10;
      output;
   end;
run;
data b;
   do i=1 to 10;
   end;
   output;
run;
data c;
   do i=1 to 10 by 2;
      output;
   end;
run;
data d;
   do j=1 to 10 by 0.5;
      output;
   end;
run;
data e;
   do k=-10 to 1 by 2;
      output;
   end;
run;
data f;
   do i=1 to 3;
      a=rannor(1);
      do j=1 to 4;
         b=ranuni(2);
         output;
      end;
   end;
run;
data g;
   do y=2001 to 2005;
      gdp=rannor(1);
      do m= 1 to 12;
         unem=rannor(2);
         do d=1 to 31;
            consumption=1000*ranuni(2);
            date=mdy(m,d,y);
            output;
         end;
      end;
   end;
run;
data code1;
   infile "D:\The Application of SAS in Financial Research\CH03\data\code.txt" firstobs=2;
      input code n;
run;
data code2;
   set code1;
      do n=1 to n;
         a=rannor(1);
         output;
      end;
run;
data code3;
   set code1;
      do y=2001 to 2002;
         do m=1 to 12;
            output;
         end;
      end;
run;
