%macro npar(variable,bit,class,year,infile,outfile);
   proc sort data=&infile;by &year &class;
   run;
   proc npar1way data=&infile;
      var &variable;
      class &class;
      by &year;
      ods output WilcoxonTest=t ;
   run;
   proc univariate data=&infile noprint;
      var &variable;
      class &class;
      by &year;
      output out=m median=&variable;
   run;
   proc transpose data=m out=m;
      var &variable;
      id &class;
      by &year;
   run;
   data t;
      set t;
         retain order 0;
         if variable^=lag(variable) then order=order+1;
   run;
   proc transpose data=t out=t;
      var nvalue1;
      id name1;
      by &year order variable;
   run;
   data &outfile;
      merge t m;
         if pl_wil<0.01 then dif=round(_0-_1,10**(-1*&bit))||'***';
         else if pl_wil<0.05 then dif=round(_0-_1,10**(-1*&bit))||'**';
         else if  pl_wil<0.1 then dif=round(_0-_1,10**(-1*&bit))||'*';
         else dif=round(_0-_1,10**(-1*&bit))||'';
		 rename _0=G1;
	     rename _1=G2;
         keep &year variable _0 _1 dif;
   run;
   proc datasets noprint;
	  save &infile &outfile;
   quit;
%mend;
