%macro ttest(variable,bit,class, year,infile,outfile);
proc sort data=&infile; by &year  &class;
run;
proc ttest data=&infile;
var &variable;
class &class;
by &year;
ods output Statistics=t;
run;
data t;
set t;
order=int((_n_-1)/3);
tv="("||left(round(mean/stderr,0.01)||')');
if abs(mean/stderr)>2.58 then m=round(mean,10**(-1*&bit))||'***';
else if abs(mean/stderr)>1.96 then m=round(mean,10**(-1*&bit))||'**';
else if abs(mean/stderr)>1.65 then m=round(mean,10**(-1*&bit))||'*';
else m=round(mean,10**(-1*&bit))||'';
if mod(_n_,3)=1 then class='G1';
if mod(_n_,3)=2 then class='G2';
if mod(_n_,3)=0 then class='Dif';
run;
proc transpose data=t out=t(drop=order _name_);
var m tv;
id class;
by &year order variable;
run;
data &outfile;
set t;
if mod(_n_,2)=0 then variable='';
run;
proc datasets noprint;
save &infile &outfile;
quit;
%mend;
