%macro FMNeweyWest(in,out,x,time,bit,lag);
proc sort data=&in;by _model_ &time;
run;
proc transpose data=&in out=&out;
var  &x;
by _model_ &time;
run;
data t;
set &in;
keep  &x;
if _n_=1 then output;
run;
proc transpose data=t out=t;
run;
data t;
set t;
t=_n_;
keep _name_ t;
run;
proc sort data=t;by _name_;
run;
proc sort data=&out;by _name_ _model_;
run;
PROC MODEL data=&out;
PARMS a;
col1 = a;
FIT col1 /GMM KERNEL=(BART,%eval(&lag+1),0);
INSTRUMENTS a;
by _name_ _model_;
ods output parameterestimates=para;
quit;
data &out;
set para;
if probt<0.01 then e=round(estimate,10**(-1*&bit))||'***';
else if probt<0.05 then e=round(estimate,10**(-1*&bit))||'**';
else if probt<0.1 then e=round(estimate,10**(-1*&bit))||'*';
else e=round(estimate,10**(-1*&bit))||'';
tv='('||left(round(tvalue,0.01)||')');
run;
proc sort data=&out;by _name_;
run;
data &out;
merge &out t;by _name_;
run;
proc sort data=&out;by t _name_ ;
run;
proc transpose data=&out out=&out (drop=t  MODEL1);
var e tv;
by  t  _name_;
id  _model_;
run;
data &out;
set &out;
lag=&lag;
run;
%mend;
