%macro reg(file,group,bit);
data &file;
   set &file;
      Ian=1;
run;
proc sort data=&file;by Ian &group;
run;
%let bit=&bit;
proc reg data=&file ;by Ian &group;
%model;
   ods output FitStatistics=fit;
   ods output NObs=nobs;
   ods output ParameterEstimates=para;
quit;

%macro OLS(White);

   %if &white=1 %then %do;
      data reg;
         set para;			  
             if HCprobt<0.01 then sig='***';
             else if HCprobt<0.05 then sig='**';
             else if Hcprobt<0.1 then sig='*';
             else sig='';
             est=round(estimate,10**(-1*&bit))||sig;
             tv='('||left(round(HCtvalue,0.01)||')');
      run;
   %end;
   %else %do;
      data reg;
         set para;			  
            if probt<0.01 then sig='***';
            else if probt<0.05 then sig='**';
            else if probt<0.1 then sig='*';
            else sig='';
            est=round(estimate,10**(-1*&bit))||sig;
            tv='('||left(round(tvalue,0.01)||')');
      run;
   %end; 
   data rsq;
      set fit;
         rsq=round(nvalue2*100,0.01)||'%';
         if label2='' then delete;
         variable=label2;
         if variable='R方' then t=1000;else t=1001;
         keep model variable rsq ian &group t;
   run;
   data n;
      set nobs;
         variable='N';
         nobs=''||nobsused;
         t=1002;
         if label='使用的观测数' then output;
   run;
   data t;
      set reg;;
         t=_n_;
         if model='MODEL1' then output;
         keep variable t;
   run;
   proc sort data=t;by variable t;
   run;
   proc sort data=t nodupkey;by variable;
   run;
   proc sort data=reg;by variable;
   run;
   data reg;
      merge reg t;by variable;
   run;
   proc sort data=reg;by &group t variable;
   run;
   proc transpose data=reg out=est;
      var est;
      by &group t variable ;
      id model;
   run;
   proc transpose data=reg out=tvalue;
      var tv;
      by &group t variable;
      id model;
   run;
   data OLS;
      set est tvalue;by &group t _name_;
         if _name_='tv' then variable='';
         drop  _name_;
   run;
   proc sort data=rsq;by &group t variable ;
   run;
   proc transpose data=rsq out=rsq;
      var rsq;
      by &group t variable ;
      id model;
   run;
   proc transpose data=n out=n;
      var nobs;
      by &group t variable;
      id model;
   run;
   data reg_ols;
      set OLS rsq n;
         %if &white=1 %then %do;
            tvalue='white';
         %end;
         %else %do;
            tvalue='OLS';
         %end;
         drop model1 _name_;
   run;
   proc sort data=reg_ols out=reg_ols(drop=t);by &group t ;
   run;
%mend;
%ols(1);
data reg_white;
   set reg_ols;
run;
%ols(0);
   proc delete data=rsq n fit est tvalue nobs reg para t;
   quit;
%mend;

